version: "3.3"
services:
  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
